# Generated by Django 2.2.16 on 2022-02-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_title_genre'),
        ('reviews', '0007_auto_20220220_1806'),
    ]

    operations = [
    ]
